### ISSUE TITLE
Foundry - Slither / Unknown file console.sol

### ISSUE THREAD

**Issue by gakonst** [crytic/crytic-compile#262]
I am trying to add Slither to the Forge template [here](https://github.com/foundry-rs/forge-template/pull/49), and getting an unexpected error:

```
ERROR:CryticCompile:Unknown file: /home/runner/work/forge-template/forge-template/lib/forge-std/src/console.sol
```

It seems to be related to [this](https://github.com/crytic/crytic-compile/blob/35d95d6cb7716290ff4bf21ba9dcc8e582c6ee04/crytic_compile/utils/naming.py#L109-L117)?

I also wonder why `forge-template` appears twice in the path?

(Separately, the Slither action does not seem to error when it hits an Error, and it makes you think that it fails at the followup step, [here the SARIF upload](https://github.com/foundry-rs/forge-template/runs/6207682054?check_suite_focus=true))

**Comment by gakonst** [comment]
@montyly gm - understand you're busy, wonder if you (or anyone else?) had any time to investigate this?

**Comment by montyly** [comment]
Hi @gakonst sorry for the delay

It might be something weird going on with slither-action's container, as running slither on the forge's template locally works. I tried using the upcoming native support for foundry within slither-action (https://github.com/crytic/slither-action/pulls), and it works https://github.com/montyly/forge-template/pull/1

```
      - name: Run Slither
        uses: crytic/slither-action@dev-install-foundry
        id: slither
        continue-on-error: true
        with:
          sarif: results.sarif
```

@elopez : any idea why the directory name would be duplicate within `slither-action`? Merging https://github.com/crytic/slither-action/pull/8 will fix the issue, but it would be better to understand why we have this behavior
